// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVpD0fLwAsulZqkYnBSLHYHVuUWe2ysCs',
    appId: '1:861920644519:web:9294f38bbb3af8861a7a82',
    messagingSenderId: '861920644519',
    projectId: 'inventory-manager-a3945',
    authDomain: 'inventory-manager-a3945.firebaseapp.com',
    storageBucket: 'inventory-manager-a3945.firebasestorage.app',
    measurementId: 'G-VCT4CCNXCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1SPnX80JLZGsXSVlF88SaX0KHe1PZ3m4',
    appId: '1:861920644519:android:c52f859305630c741a7a82',
    messagingSenderId: '861920644519',
    projectId: 'inventory-manager-a3945',
    storageBucket: 'inventory-manager-a3945.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPXZNLQlOCMfwZh5QHVnOTrM1QGsJk3n0',
    appId: '1:861920644519:ios:8d30eba03652ed871a7a82',
    messagingSenderId: '861920644519',
    projectId: 'inventory-manager-a3945',
    storageBucket: 'inventory-manager-a3945.firebasestorage.app',
    iosBundleId: 'com.example.inventoryManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPXZNLQlOCMfwZh5QHVnOTrM1QGsJk3n0',
    appId: '1:861920644519:ios:8d30eba03652ed871a7a82',
    messagingSenderId: '861920644519',
    projectId: 'inventory-manager-a3945',
    storageBucket: 'inventory-manager-a3945.firebasestorage.app',
    iosBundleId: 'com.example.inventoryManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVpD0fLwAsulZqkYnBSLHYHVuUWe2ysCs',
    appId: '1:861920644519:web:695cb2ee697aa23a1a7a82',
    messagingSenderId: '861920644519',
    projectId: 'inventory-manager-a3945',
    authDomain: 'inventory-manager-a3945.firebaseapp.com',
    storageBucket: 'inventory-manager-a3945.firebasestorage.app',
    measurementId: 'G-8JQ1Z9SV4N',
  );
}
